app = "xe-palworld"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[mounts]]
  source = "steam"
  destination = "/home/steam/palworld"
  initial_size = "20GB"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "20GB"

[[services]]
  protocol = "udp"
  internal_port = 8211
  processes = ["app"]
  
  [[services.ports]]
    port = 8211

[[services]]
  protocol = "tcp"
  internal_port = 8211
  processes = ["app"]

  [[services.ports]]
    port = 8211
